/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderId?: string;
  customer?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "customer";
  };
  clerkUserId?: string;
  items?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    title?: string;
    price?: number;
    quantity?: number;
    _key: string;
  }>;
  subtotal?: number;
  shippingCost?: number;
  totalAmount?: number;
  payment?: {
    method?: "card" | "upi" | "cod";
    status?: "pending" | "paid" | "failed" | "refunded";
    stripePaymentIntentId?: string;
  };
  shippingAddress?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  };
  status?: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
  createdAt?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  price?: number;
  discountPrice?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  inStock?: boolean;
  quantity?: number;
  featured?: boolean;
  createdAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  clerkUserId?: string;
  stripeCustomerId?: string;
  createdAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Order | Product | SanityImageCrop | SanityImageHotspot | Slug | Category | Customer | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/categories.ts
// Variable: All_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    "image": image {      asset->{        _id,        url      },      hotspot    }  }
export type All_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[    _type == "category"    && slug.current == $slug    ][0] {    _id,    title,    "slug":slug.current,    "image":image{    asset->{    _id,    url    },    hotspot}    }
export type CATEGORY_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: ./sanity/queries/customers.ts
// Variable: CUSTOMER_BY_EMAIL_QUERY
// Query: *[_type == "customer" && email == $email][0] {    _id,    email,    name,    clerkUserId,    stripeCustomerId,    createdAt  }
export type CUSTOMER_BY_EMAIL_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string | null;
  createdAt: string | null;
} | null;
// Variable: CUSTOMER_BY_CLERK_ID_QUERY
// Query: *[_type == "customer" && clerkUserId == $clerkUserId][0] {    _id,    email,    name,    clerkUserId,    stripeCustomerId,    createdAt  }
export type CUSTOMER_BY_CLERK_ID_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string | null;
  createdAt: string | null;
} | null;

// Source: ./sanity/queries/orders.ts
// Variable: ALL_ORDERS_QUERY
// Query: *[_type == "order"] | order(createdAt desc) {    _id,    orderId,    status,    totalAmount,    createdAt,    "customer": customer->{      _id,      name,      email    }  }
export type ALL_ORDERS_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
  customer: {
    _id: string;
    name: string | null;
    email: string | null;
  } | null;
}>;
// Variable: ORDERS_BY_STATUS_QUERY
// Query: *[_type == "order" && status == $status]  | order(createdAt desc) {    _id,    orderId,    status,    totalAmount,    createdAt,    customer->{      name,      email    }  }
export type ORDERS_BY_STATUS_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
  customer: {
    name: string | null;
    email: string | null;
  } | null;
}>;
// Variable: RECENT_ORDERS_QUERY
// Query: *[_type == "order"] | order(createdAt desc)[0...5] {    _id,    orderId,    status,    totalAmount,    createdAt  }
export type RECENT_ORDERS_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
}>;
// Variable: ORDERS_COUNT_QUERY
// Query: count(*[_type == "order"])
export type ORDERS_COUNT_QUERYResult = number;
// Variable: ORDER_BY_ORDER_ID_QUERY
// Query: *[_type == "order" && orderId == $orderId][0] {    _id,    orderId,    status,    subtotal,    shippingCost,    totalAmount,    createdAt,    customer->{      _id,      name,      email,      stripeCustomerId    },    items[]{      title,      price,      quantity,      product->{        _id,        title,        slug      }    },    shippingAddress,    payment  }
export type ORDER_BY_ORDER_ID_QUERYResult = {
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  subtotal: number | null;
  shippingCost: number | null;
  totalAmount: number | null;
  createdAt: string | null;
  customer: {
    _id: string;
    name: string | null;
    email: string | null;
    stripeCustomerId: string | null;
  } | null;
  items: Array<{
    title: string | null;
    price: number | null;
    quantity: number | null;
    product: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
  }> | null;
  shippingAddress: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  } | null;
  payment: {
    method?: "card" | "cod" | "upi";
    status?: "failed" | "paid" | "pending" | "refunded";
    stripePaymentIntentId?: string;
  } | null;
} | null;
// Variable: ORDERS_BY_CLERK_USER_QUERY
// Query: *[_type == "order" && clerkUserId == $clerkUserId]  | order(createdAt desc) {    _id,    orderId,    status,    totalAmount,    createdAt  }
export type ORDERS_BY_CLERK_USER_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
}>;
// Variable: ORDERS_BY_CUSTOMER_ID_QUERY
// Query: *[_type == "order" && customer._ref == $customerId]  | order(createdAt desc) {    _id,    orderId,    status,    totalAmount,    createdAt  }
export type ORDERS_BY_CUSTOMER_ID_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
}>;

// Source: ./sanity/queries/products.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product"] | order(_createdAt desc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && _id == $id][0]  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type PRODUCT_BY_ID_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
} | null;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
} | null;
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[_type == "product" && $categorySlug in categories[]->slug.current]  | order(_createdAt desc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type PRODUCTS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: SEARCH_PRODUCTS_BY_NAME_QUERY
// Query: *[_type == "product" && title match $search + "*"]  | order(_createdAt desc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type SEARCH_PRODUCTS_BY_NAME_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: PRODUCTS_PRICE_ASC_QUERY
// Query: *[_type == "product"] | order(price asc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type PRODUCTS_PRICE_ASC_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: PRODUCTS_PRICE_DESC_QUERY
// Query: *[_type == "product"] | order(price desc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type PRODUCTS_PRICE_DESC_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: PRODUCTS_BY_PRICE_RANGE_QUERY
// Query: *[_type == "product" && price >= $min && price <= $max]  | order(price asc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type PRODUCTS_BY_PRICE_RANGE_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: IN_STOCK_PRODUCTS_QUERY
// Query: *[_type == "product" && inStock == true]  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type IN_STOCK_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: true;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: OUT_OF_STOCK_PRODUCTS_QUERY
// Query: *[_type == "product" && inStock == false]  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type OUT_OF_STOCK_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: false;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: LOW_STOCK_PRODUCTS_QUERY
// Query: *[_type == "product" && quantity < $threshold]  | order(quantity asc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type LOW_STOCK_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[_type == "product" && featured == true]  | order(_createdAt desc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type FEATURED_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: true;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: DISCOUNTED_PRODUCTS_QUERY
// Query: *[_type == "product" && defined(discountPrice)]  | order(discountPrice asc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type DISCOUNTED_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: NEW_ARRIVALS_QUERY
// Query: *[_type == "product"]  | order(_createdAt desc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type NEW_ARRIVALS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: BEST_SELLER_PRODUCTS_QUERY
// Query: *[_type == "product"]  | order(quantity desc)  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type BEST_SELLER_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: PAGINATED_PRODUCTS_QUERY
// Query: *[_type == "product"]  | order(_createdAt desc)[$start...$end]  {  _id,  title,  "slug": slug.current,  price,  discountPrice,  inStock,  quantity,  featured,  description,  categories[]->{    _id,    title,    "slug": slug.current  },  images[]{    asset->{      _id,      url    },    hotspot  }}
export type PAGINATED_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  featured: boolean | null;
  description: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  images: null;
}>;
// Variable: PRODUCT_COUNT_QUERY
// Query: count(*[_type == "product"])
export type PRODUCT_COUNT_QUERYResult = number;
// Variable: OUT_OF_STOCK_COUNT_QUERY
// Query: count(*[_type == "product" && inStock == false])
export type OUT_OF_STOCK_COUNT_QUERYResult = number;
// Variable: LOW_STOCK_COUNT_QUERY
// Query: count(*[_type == "product" && quantity < $threshold])
export type LOW_STOCK_COUNT_QUERYResult = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"category\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    \"image\": image {\n      asset->{\n        _id,\n        url\n      },\n      hotspot\n    }\n  }\n": All_CATEGORIES_QUERYResult;
    "*[\n    _type == \"category\"\n    && slug.current == $slug\n    ][0] {\n    _id,\n    title,\n    \"slug\":slug.current,\n    \"image\":image{\n    asset->{\n    _id,\n    url\n    },\n    hotspot}\n    }": CATEGORY_BY_SLUG_QUERYResult;
    "\n  *[_type == \"customer\" && email == $email][0] {\n    _id,\n    email,\n    name,\n    clerkUserId,\n    stripeCustomerId,\n    createdAt\n  }\n": CUSTOMER_BY_EMAIL_QUERYResult;
    "\n  *[_type == \"customer\" && clerkUserId == $clerkUserId][0] {\n    _id,\n    email,\n    name,\n    clerkUserId,\n    stripeCustomerId,\n    createdAt\n  }\n": CUSTOMER_BY_CLERK_ID_QUERYResult;
    "\n  *[_type == \"order\"] | order(createdAt desc) {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt,\n    \"customer\": customer->{\n      _id,\n      name,\n      email\n    }\n  }\n": ALL_ORDERS_QUERYResult;
    "\n  *[_type == \"order\" && status == $status]\n  | order(createdAt desc) {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt,\n    customer->{\n      name,\n      email\n    }\n  }\n": ORDERS_BY_STATUS_QUERYResult;
    "\n  *[_type == \"order\"] | order(createdAt desc)[0...5] {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt\n  }\n": RECENT_ORDERS_QUERYResult;
    "\n  count(*[_type == \"order\"])\n": ORDERS_COUNT_QUERYResult;
    "\n  *[_type == \"order\" && orderId == $orderId][0] {\n    _id,\n    orderId,\n    status,\n    subtotal,\n    shippingCost,\n    totalAmount,\n    createdAt,\n\n    customer->{\n      _id,\n      name,\n      email,\n      stripeCustomerId\n    },\n\n    items[]{\n      title,\n      price,\n      quantity,\n      product->{\n        _id,\n        title,\n        slug\n      }\n    },\n\n    shippingAddress,\n    payment\n  }\n": ORDER_BY_ORDER_ID_QUERYResult;
    "\n  *[_type == \"order\" && clerkUserId == $clerkUserId]\n  | order(createdAt desc) {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt\n  }\n": ORDERS_BY_CLERK_USER_QUERYResult;
    "\n  *[_type == \"order\" && customer._ref == $customerId]\n  | order(createdAt desc) {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt\n  }\n": ORDERS_BY_CUSTOMER_ID_QUERYResult;
    "\n  *[_type == \"product\"] | order(_createdAt desc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": ALL_PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\" && _id == $id][0]\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": PRODUCT_BY_ID_QUERYResult;
    "\n  *[_type == \"product\" && slug.current == $slug][0]\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": PRODUCT_BY_SLUG_QUERYResult;
    "\n  *[_type == \"product\" && $categorySlug in categories[]->slug.current]\n  | order(_createdAt desc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": PRODUCTS_BY_CATEGORY_QUERYResult;
    "\n  *[_type == \"product\" && title match $search + \"*\"]\n  | order(_createdAt desc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": SEARCH_PRODUCTS_BY_NAME_QUERYResult;
    "\n  *[_type == \"product\"] | order(price asc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": PRODUCTS_PRICE_ASC_QUERYResult;
    "\n  *[_type == \"product\"] | order(price desc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": PRODUCTS_PRICE_DESC_QUERYResult;
    "\n  *[_type == \"product\" && price >= $min && price <= $max]\n  | order(price asc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": PRODUCTS_BY_PRICE_RANGE_QUERYResult;
    "\n  *[_type == \"product\" && inStock == true]\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": IN_STOCK_PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\" && inStock == false]\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": OUT_OF_STOCK_PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\" && quantity < $threshold]\n  | order(quantity asc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": LOW_STOCK_PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\" && featured == true]\n  | order(_createdAt desc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": FEATURED_PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\" && defined(discountPrice)]\n  | order(discountPrice asc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": DISCOUNTED_PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\"]\n  | order(_createdAt desc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": NEW_ARRIVALS_QUERYResult;
    "\n  *[_type == \"product\"]\n  | order(quantity desc)\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": BEST_SELLER_PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\"]\n  | order(_createdAt desc)[$start...$end]\n  \n{\n  _id,\n  title,\n  \"slug\": slug.current,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  featured,\n  description,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  images[]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}\n\n": PAGINATED_PRODUCTS_QUERYResult;
    "\n  count(*[_type == \"product\"])\n": PRODUCT_COUNT_QUERYResult;
    "\n  count(*[_type == \"product\" && inStock == false])\n": OUT_OF_STOCK_COUNT_QUERYResult;
    "\n  count(*[_type == \"product\" && quantity < $threshold])\n": LOW_STOCK_COUNT_QUERYResult;
  }
}
