/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderId?: string;
  customer?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "customer";
  };
  clerkUserId?: string;
  items?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    title?: string;
    price?: number;
    quantity?: number;
    _key: string;
  }>;
  subtotal?: number;
  shippingCost?: number;
  totalAmount?: number;
  payment?: {
    method?: "card" | "upi" | "cod";
    status?: "pending" | "paid" | "failed" | "refunded";
    stripePaymentIntentId?: string;
  };
  shippingAddress?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  };
  status?: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
  createdAt?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  price?: number;
  discountPrice?: number;
  colors?: Array<{
    name?: string;
    hex?: string;
    _key: string;
  }>;
  sizes?: Array<string>;
  variants?: Array<{
    sku?: string;
    color?: string;
    size?: string;
    price?: number;
    inStock?: boolean;
    quantity?: number;
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  inStock?: boolean;
  quantity?: number;
  featured?: boolean;
  createdAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  clerkUserId?: string;
  stripeCustomerId?: string;
  createdAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Order | Product | SanityImageCrop | SanityImageHotspot | Slug | Category | Customer | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/categories.ts
// Variable: All_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    "image": image {      asset->{        _id,        url      },      hotspot    }  }
export type All_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[    _type == "category"    && slug.current == $slug    ][0] {    _id,    title,    "slug":slug.current,    "image":image{    asset->{    _id,    url    },    hotspot}    }
export type CATEGORY_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: ./sanity/queries/customers.ts
// Variable: CUSTOMER_BY_EMAIL_QUERY
// Query: *[_type == "customer" && email == $email][0] {    _id,    email,    name,    clerkUserId,    stripeCustomerId,    createdAt  }
export type CUSTOMER_BY_EMAIL_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string | null;
  createdAt: string | null;
} | null;
// Variable: CUSTOMER_BY_CLERK_ID_QUERY
// Query: *[_type == "customer" && clerkUserId == $clerkUserId][0] {    _id,    email,    name,    clerkUserId,    stripeCustomerId,    createdAt  }
export type CUSTOMER_BY_CLERK_ID_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string | null;
  createdAt: string | null;
} | null;

// Source: ./sanity/queries/orders.ts
// Variable: ALL_ORDERS_QUERY
// Query: *[_type == "order"] | order(createdAt desc) {    _id,    orderId,    status,    totalAmount,    createdAt,    "customer": customer->{      _id,      name,      email    }  }
export type ALL_ORDERS_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
  customer: {
    _id: string;
    name: string | null;
    email: string | null;
  } | null;
}>;
// Variable: ORDERS_BY_STATUS_QUERY
// Query: *[_type == "order" && status == $status]  | order(createdAt desc) {    _id,    orderId,    status,    totalAmount,    createdAt,    customer->{      name,      email    }  }
export type ORDERS_BY_STATUS_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
  customer: {
    name: string | null;
    email: string | null;
  } | null;
}>;
// Variable: RECENT_ORDERS_QUERY
// Query: *[_type == "order"] | order(createdAt desc)[0...5] {    _id,    orderId,    status,    totalAmount,    createdAt  }
export type RECENT_ORDERS_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
}>;
// Variable: ORDERS_COUNT_QUERY
// Query: count(*[_type == "order"])
export type ORDERS_COUNT_QUERYResult = number;
// Variable: TOTAL_REVENUE_QUERY
// Query: {  "totalRevenue": math::sum(    *[_type == "order" && status == "completed"].total  )}
export type TOTAL_REVENUE_QUERYResult = {
  totalRevenue: never;
};
// Variable: ORDER_BY_ORDER_ID_QUERY
// Query: *[_type == "order" && orderId == $orderId][0] {    _id,    orderId,    status,    subtotal,    shippingCost,    totalAmount,    createdAt,    customer->{      _id,      name,      email,      stripeCustomerId    },    items[]{      title,      price,      quantity,      product->{        _id,        title,        slug      }    },    shippingAddress,    payment  }
export type ORDER_BY_ORDER_ID_QUERYResult = {
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  subtotal: number | null;
  shippingCost: number | null;
  totalAmount: number | null;
  createdAt: string | null;
  customer: {
    _id: string;
    name: string | null;
    email: string | null;
    stripeCustomerId: string | null;
  } | null;
  items: Array<{
    title: string | null;
    price: number | null;
    quantity: number | null;
    product: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
  }> | null;
  shippingAddress: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  } | null;
  payment: {
    method?: "card" | "cod" | "upi";
    status?: "failed" | "paid" | "pending" | "refunded";
    stripePaymentIntentId?: string;
  } | null;
} | null;
// Variable: ORDERS_BY_CLERK_USER_QUERY
// Query: *[_type == "order" && clerkUserId == $clerkUserId]  | order(createdAt desc) {    _id,    orderId,    status,    totalAmount,    createdAt  }
export type ORDERS_BY_CLERK_USER_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
}>;
// Variable: ORDERS_BY_CUSTOMER_ID_QUERY
// Query: *[_type == "order" && customer._ref == $customerId]  | order(createdAt desc) {    _id,    orderId,    status,    totalAmount,    createdAt  }
export type ORDERS_BY_CUSTOMER_ID_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  totalAmount: number | null;
  createdAt: string | null;
}>;

// Source: ./sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_MASTER_QUERY
// Query: *[  _type == "product"  && (!defined($search) || title match $search + "*")  && (!defined($category) || $category in categories[]->slug.current)  && (!defined($minPrice) || price >= $minPrice)  && (!defined($maxPrice) || price <= $maxPrice)  && (!defined($inStock) || inStock == $inStock)] | order(  select($sort == "price_asc" => price) asc,  select($sort == "price_desc" => price) desc,  select($sort == "newest" => _createdAt) desc,  title asc)[$start...$end] {    _id,  title,  description,  price,  discountPrice,  featured,  inStock,  quantity,  _createdAt,  createdAt,  slug {    current  },  image {    asset->{      _id,      url    }  },  gallery[] {    asset->{      _id,      url    }  },  categories[]->{    _id,    title,    slug {      current    }  },  colors[]{    name,    hex  },  sizes,  variants[]{    sku,    color,    size,    price,    inStock,    quantity  }}
export type FILTER_PRODUCTS_MASTER_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  discountPrice: number | null;
  featured: boolean | null;
  inStock: boolean | null;
  quantity: number | null;
  _createdAt: string;
  createdAt: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: {
      current: string | null;
    } | null;
  }> | null;
  colors: Array<{
    name: string | null;
    hex: string | null;
  }> | null;
  sizes: Array<string> | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: string | null;
    price: number | null;
    inStock: boolean | null;
    quantity: number | null;
  }> | null;
}>;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{  _id,  title,  description,  price,  discountPrice,  inStock,  quantity,  createdAt,  "images": gallery[].asset->url,  categories[]->{    _id,    title,    "slug": slug.current  },  colors[]{    name,    hex  },  sizes,  variants[]{    sku,    color,    size,    price,    inStock,    quantity  }}
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  discountPrice: number | null;
  inStock: boolean | null;
  quantity: number | null;
  createdAt: string | null;
  images: Array<string | null> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  colors: Array<{
    name: string | null;
    hex: string | null;
  }> | null;
  sizes: Array<string> | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: string | null;
    price: number | null;
    inStock: boolean | null;
    quantity: number | null;
  }> | null;
} | null;
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[_type == "product" && featured == true] | order(_createdAt desc) {   _id,  title,  description,  price,  discountPrice,  featured,  inStock,  quantity,  _createdAt,  createdAt,  slug {    current  },  image {    asset->{      _id,      url    }  },  gallery[] {    asset->{      _id,      url    }  },  categories[]->{    _id,    title,    slug {      current    }  },  colors[]{    name,    hex  },  sizes,  variants[]{    sku,    color,    size,    price,    inStock,    quantity  } }
export type FEATURED_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  discountPrice: number | null;
  featured: true;
  inStock: boolean | null;
  quantity: number | null;
  _createdAt: string;
  createdAt: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: {
      current: string | null;
    } | null;
  }> | null;
  colors: Array<{
    name: string | null;
    hex: string | null;
  }> | null;
  sizes: Array<string> | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: string | null;
    price: number | null;
    inStock: boolean | null;
    quantity: number | null;
  }> | null;
}>;
// Variable: FILTERED_PRODUCT_COUNT_QUERY
// Query: count(  *[    _type == "product"    && (!defined($search) || title match $search + "*")    && (!defined($category) || $category in categories[]->slug.current)    && (!defined($minPrice) || price >= $minPrice)    && (!defined($maxPrice) || price <= $maxPrice)    && (!defined($inStock) || inStock == $inStock)  ])
export type FILTERED_PRODUCT_COUNT_QUERYResult = number;
// Variable: FILTER_PRODUCTS_BY_NAME_QUERY
// Query: *[  _type == "product"  // Only filter by name if $name is actually provided  && (!defined($name) || title match $name + "*")] | order(title asc) {    _id,  title,  description,  price,  discountPrice,  featured,  inStock,  quantity,  _createdAt,  createdAt,  slug {    current  },  image {    asset->{      _id,      url    }  },  gallery[] {    asset->{      _id,      url    }  },  categories[]->{    _id,    title,    slug {      current    }  },  colors[]{    name,    hex  },  sizes,  variants[]{    sku,    color,    size,    price,    inStock,    quantity  }}
export type FILTER_PRODUCTS_BY_NAME_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  discountPrice: number | null;
  featured: boolean | null;
  inStock: boolean | null;
  quantity: number | null;
  _createdAt: string;
  createdAt: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: {
      current: string | null;
    } | null;
  }> | null;
  colors: Array<{
    name: string | null;
    hex: string | null;
  }> | null;
  sizes: Array<string> | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: string | null;
    price: number | null;
    inStock: boolean | null;
    quantity: number | null;
  }> | null;
}>;
// Variable: FILTER_PRODUCTS_BY_PRICE_ASC_QUERY
// Query: *[_type == "product"] | order(price asc) {      _id,  title,  description,  price,  discountPrice,  featured,  inStock,  quantity,  _createdAt,  createdAt,  slug {    current  },  image {    asset->{      _id,      url    }  },  gallery[] {    asset->{      _id,      url    }  },  categories[]->{    _id,    title,    slug {      current    }  },  colors[]{    name,    hex  },  sizes,  variants[]{    sku,    color,    size,    price,    inStock,    quantity  }  }
export type FILTER_PRODUCTS_BY_PRICE_ASC_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  discountPrice: number | null;
  featured: boolean | null;
  inStock: boolean | null;
  quantity: number | null;
  _createdAt: string;
  createdAt: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: {
      current: string | null;
    } | null;
  }> | null;
  colors: Array<{
    name: string | null;
    hex: string | null;
  }> | null;
  sizes: Array<string> | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: string | null;
    price: number | null;
    inStock: boolean | null;
    quantity: number | null;
  }> | null;
}>;
// Variable: FILTER_PRODUCTS_BY_PRICE_DESC_QUERY
// Query: *[_type == "product"] | order(price desc) [$start...$end] {      _id,  title,  description,  price,  discountPrice,  featured,  inStock,  quantity,  _createdAt,  createdAt,  slug {    current  },  image {    asset->{      _id,      url    }  },  gallery[] {    asset->{      _id,      url    }  },  categories[]->{    _id,    title,    slug {      current    }  },  colors[]{    name,    hex  },  sizes,  variants[]{    sku,    color,    size,    price,    inStock,    quantity  }  }
export type FILTER_PRODUCTS_BY_PRICE_DESC_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  discountPrice: number | null;
  featured: boolean | null;
  inStock: boolean | null;
  quantity: number | null;
  _createdAt: string;
  createdAt: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: {
      current: string | null;
    } | null;
  }> | null;
  colors: Array<{
    name: string | null;
    hex: string | null;
  }> | null;
  sizes: Array<string> | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: string | null;
    price: number | null;
    inStock: boolean | null;
    quantity: number | null;
  }> | null;
}>;
// Variable: FILTER_PRODUCTS_BY_RELEVANCE_QUERY
// Query: *[_type == "product" && (title match $search + "*" || description match $search + "*")] | order(  select(    title match $search + "*" => 2,    description match $search + "*" => 1,    0  ) desc,  title asc) [$start...$end] {    _id,  title,  description,  price,  discountPrice,  featured,  inStock,  quantity,  _createdAt,  createdAt,  slug {    current  },  image {    asset->{      _id,      url    }  },  gallery[] {    asset->{      _id,      url    }  },  categories[]->{    _id,    title,    slug {      current    }  },  colors[]{    name,    hex  },  sizes,  variants[]{    sku,    color,    size,    price,    inStock,    quantity  }}
export type FILTER_PRODUCTS_BY_RELEVANCE_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  discountPrice: number | null;
  featured: boolean | null;
  inStock: boolean | null;
  quantity: number | null;
  _createdAt: string;
  createdAt: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: {
      current: string | null;
    } | null;
  }> | null;
  colors: Array<{
    name: string | null;
    hex: string | null;
  }> | null;
  sizes: Array<string> | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: string | null;
    price: number | null;
    inStock: boolean | null;
    quantity: number | null;
  }> | null;
}>;
// Variable: PRODUCTS_BY_IDS_QUERY
// Query: *[_type == "product" && _id in $ids] {    _id,    quantity  }
export type PRODUCTS_BY_IDS_QUERYResult = Array<{
  _id: string;
  quantity: number | null;
}>;

// Source: ./sanity/queries/stats.ts
// Variable: TOTAL_PRODUCTS_QUERY
// Query: count(*[_type == "product"])
export type TOTAL_PRODUCTS_QUERYResult = number;
// Variable: IN_STOCK_PRODUCTS_COUNT_QUERY
// Query: count(*[_type == "product" && inStock == true])
export type IN_STOCK_PRODUCTS_COUNT_QUERYResult = number;
// Variable: OUT_OF_STOCK_PRODUCTS_COUNT_QUERY
// Query: count(*[_type == "product" && inStock == false])
export type OUT_OF_STOCK_PRODUCTS_COUNT_QUERYResult = number;
// Variable: LOW_STOCK_PRODUCTS_COUNT_QUERY
// Query: count(*[_type == "product" && quantity < $threshold])
export type LOW_STOCK_PRODUCTS_COUNT_QUERYResult = number;
// Variable: FEATURED_PRODUCTS_COUNT_QUERY
// Query: count(*[_type == "product" && featured == true])
export type FEATURED_PRODUCTS_COUNT_QUERYResult = number;
// Variable: DISCOUNTED_PRODUCTS_COUNT_QUERY
// Query: count(*[_type == "product" && defined(discountPrice)])
export type DISCOUNTED_PRODUCTS_COUNT_QUERYResult = number;
// Variable: TOTAL_CATEGORIES_QUERY
// Query: count(*[_type == "category"])
export type TOTAL_CATEGORIES_QUERYResult = number;
// Variable: TOTAL_CUSTOMERS_QUERY
// Query: count(*[_type == "customer"])
export type TOTAL_CUSTOMERS_QUERYResult = number;
// Variable: STRIPE_CUSTOMERS_COUNT_QUERY
// Query: count(*[_type == "customer" && defined(stripeCustomerId)])
export type STRIPE_CUSTOMERS_COUNT_QUERYResult = number;
// Variable: TOTAL_ORDERS_QUERY
// Query: count(*[_type == "order"])
export type TOTAL_ORDERS_QUERYResult = number;
// Variable: PENDING_ORDERS_COUNT_QUERY
// Query: count(*[_type == "order" && status == "pending"])
export type PENDING_ORDERS_COUNT_QUERYResult = number;
// Variable: PROCESSING_ORDERS_COUNT_QUERY
// Query: count(*[_type == "order" && status == "processing"])
export type PROCESSING_ORDERS_COUNT_QUERYResult = number;
// Variable: SHIPPED_ORDERS_COUNT_QUERY
// Query: count(*[_type == "order" && status == "shipped"])
export type SHIPPED_ORDERS_COUNT_QUERYResult = number;
// Variable: DELIVERED_ORDERS_COUNT_QUERY
// Query: count(*[_type == "order" && status == "delivered"])
export type DELIVERED_ORDERS_COUNT_QUERYResult = number;
// Variable: CANCELLED_ORDERS_COUNT_QUERY
// Query: count(*[_type == "order" && status == "cancelled"])
export type CANCELLED_ORDERS_COUNT_QUERYResult = number;
// Variable: STATS_TOTAL_REVENUE_QUERY
// Query: {    "totalRevenue": math::sum(      *[_type == "order" && status == "completed"].total    )  }
export type STATS_TOTAL_REVENUE_QUERYResult = {
  totalRevenue: never;
};
// Variable: TODAY_REVENUE_QUERY
// Query: {  "todayRevenue": math::sum(    *[      _type == "order"      && status == "completed"      && createdAt >= dateTime(now()) - 60*60*24    ].total  )}
export type TODAY_REVENUE_QUERYResult = {
  todayRevenue: never;
};
// Variable: MONTH_REVENUE_QUERY
// Query: {  "monthRevenue": math::sum(    *[      _type == "order"      && status == "completed"      && createdAt >= dateTime(now()) - 60*60*24*30    ].total  )}
export type MONTH_REVENUE_QUERYResult = {
  monthRevenue: never;
};
// Variable: AVERAGE_ORDER_VALUE_QUERY
// Query: math::avg(*[_type == "order" && status == "paid"].totalAmount)
export type AVERAGE_ORDER_VALUE_QUERYResult = never;
// Variable: MAX_ORDER_VALUE_QUERY
// Query: math::max(*[_type == "order" && status == "paid"].totalAmount)
export type MAX_ORDER_VALUE_QUERYResult = never;
// Variable: ATTENTION_ORDERS_COUNT_QUERY
// Query: count(    *[      _type == "order" &&      (status == "pending" || status == "processing")    ]  )
export type ATTENTION_ORDERS_COUNT_QUERYResult = number;
// Variable: ORDERS_LAST_7_DAYS_QUERY
// Query: *[  _type == "order"  && createdAt >= dateTime(now()) - 60*60*24*7]
export type ORDERS_LAST_7_DAYS_QUERYResult = Array<never>;
// Variable: ORDERS_LAST_7_DAYS_COUNT_QUERY
// Query: count(  *[    _type == "order"    && createdAt >= dateTime(now()) - 60*60*24*7  ])
export type ORDERS_LAST_7_DAYS_COUNT_QUERYResult = number;
// Variable: ORDER_STATUS_DISTRIBUTION_QUERY
// Query: {  "pending": count(*[_type == "order" && status == "pending"]),  "processing": count(*[_type == "order" && status == "processing"]),  "shipped": count(*[_type == "order" && status == "shipped"]),  "delivered": count(*[_type == "order" && status == "delivered"]),  "cancelled": count(*[_type == "order" && status == "cancelled"])}
export type ORDER_STATUS_DISTRIBUTION_QUERYResult = {
  pending: number;
  processing: number;
  shipped: number;
  delivered: number;
  cancelled: number;
};
// Variable: TOP_SELLING_PRODUCTS_QUERY
// Query: *[_type == "product"] {      _id,  title,  description,  price,  discountPrice,  featured,  inStock,  quantity,  _createdAt,  createdAt,  slug {    current  },  image {    asset->{      _id,      url    }  },  gallery[] {    asset->{      _id,      url    }  },  categories[]->{    _id,    title,    slug {      current    }  },  colors[]{    name,    hex  },  sizes,  variants[]{    sku,    color,    size,    price,    inStock,    quantity  },    "salesCount": count(*[_type == "order" && references(^._id)])  } | order(salesCount desc)[0...5]
export type TOP_SELLING_PRODUCTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  price: number | null;
  discountPrice: number | null;
  featured: boolean | null;
  inStock: boolean | null;
  quantity: number | null;
  _createdAt: string;
  createdAt: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: {
      current: string | null;
    } | null;
  }> | null;
  colors: Array<{
    name: string | null;
    hex: string | null;
  }> | null;
  sizes: Array<string> | null;
  variants: Array<{
    sku: string | null;
    color: string | null;
    size: string | null;
    price: number | null;
    inStock: boolean | null;
    quantity: number | null;
  }> | null;
  salesCount: number;
}>;
// Variable: TOP_SELLING_PRODUCTS_AGGREGATED_QUERY
// Query: *[_type == "product"] {    _id,    title,    "totalRevenue": math::sum(*[_type == "order" && references(^._id)].items[product._ref == ^.^._id].price)  } | order(totalRevenue desc)[0...5]
export type TOP_SELLING_PRODUCTS_AGGREGATED_QUERYResult = Array<{
  _id: string;
  title: string | null;
  totalRevenue: number;
}>;
// Variable: UNFULFILLED_ORDERS_QUERY
// Query: *[    _type == "order" &&    (      status == "pending" ||      status == "processing"    )  ] | order(createdAt asc) {    _id,    orderId,    totalAmount,    status,    createdAt,    customer->{      _id,      name,      email    },    items[]{      title,      quantity    }  }
export type UNFULFILLED_ORDERS_QUERYResult = Array<{
  _id: string;
  orderId: string | null;
  totalAmount: number | null;
  status: "cancelled" | "delivered" | "pending" | "processing" | "shipped" | null;
  createdAt: string | null;
  customer: {
    _id: string;
    name: string | null;
    email: string | null;
  } | null;
  items: Array<{
    title: string | null;
    quantity: number | null;
  }> | null;
}>;
// Variable: UNFULFILLED_ORDERS_COUNT_QUERY
// Query: count(    *[      _type == "order" &&      (status == "pending" || status == "processing")    ]  )
export type UNFULFILLED_ORDERS_COUNT_QUERYResult = number;
// Variable: SALES_LAST_7_DAYS_QUERY
// Query: {  "salesLast7Days": math::sum(    *[      _type == "order"      && status == "completed"      && createdAt >= dateTime(now()) - 60*60*24*7    ].total  )}
export type SALES_LAST_7_DAYS_QUERYResult = {
  salesLast7Days: never;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"category\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    \"image\": image {\n      asset->{\n        _id,\n        url\n      },\n      hotspot\n    }\n  }\n": All_CATEGORIES_QUERYResult;
    "*[\n    _type == \"category\"\n    && slug.current == $slug\n    ][0] {\n    _id,\n    title,\n    \"slug\":slug.current,\n    \"image\":image{\n    asset->{\n    _id,\n    url\n    },\n    hotspot}\n    }": CATEGORY_BY_SLUG_QUERYResult;
    "\n  *[_type == \"customer\" && email == $email][0] {\n    _id,\n    email,\n    name,\n    clerkUserId,\n    stripeCustomerId,\n    createdAt\n  }\n": CUSTOMER_BY_EMAIL_QUERYResult;
    "\n  *[_type == \"customer\" && clerkUserId == $clerkUserId][0] {\n    _id,\n    email,\n    name,\n    clerkUserId,\n    stripeCustomerId,\n    createdAt\n  }\n": CUSTOMER_BY_CLERK_ID_QUERYResult;
    "\n  *[_type == \"order\"] | order(createdAt desc) {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt,\n    \"customer\": customer->{\n      _id,\n      name,\n      email\n    }\n  }\n": ALL_ORDERS_QUERYResult;
    "\n  *[_type == \"order\" && status == $status]\n  | order(createdAt desc) {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt,\n    customer->{\n      name,\n      email\n    }\n  }\n": ORDERS_BY_STATUS_QUERYResult;
    "\n  *[_type == \"order\"] | order(createdAt desc)[0...5] {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt\n  }\n": RECENT_ORDERS_QUERYResult;
    "\n  count(*[_type == \"order\"])\n": ORDERS_COUNT_QUERYResult | TOTAL_ORDERS_QUERYResult;
    "\n{\n  \"totalRevenue\": math::sum(\n    *[_type == \"order\" && status == \"completed\"].total\n  )\n}\n": TOTAL_REVENUE_QUERYResult;
    "\n  *[_type == \"order\" && orderId == $orderId][0] {\n    _id,\n    orderId,\n    status,\n    subtotal,\n    shippingCost,\n    totalAmount,\n    createdAt,\n\n    customer->{\n      _id,\n      name,\n      email,\n      stripeCustomerId\n    },\n\n    items[]{\n      title,\n      price,\n      quantity,\n      product->{\n        _id,\n        title,\n        slug\n      }\n    },\n\n    shippingAddress,\n    payment\n  }\n": ORDER_BY_ORDER_ID_QUERYResult;
    "\n  *[_type == \"order\" && clerkUserId == $clerkUserId]\n  | order(createdAt desc) {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt\n  }\n": ORDERS_BY_CLERK_USER_QUERYResult;
    "\n  *[_type == \"order\" && customer._ref == $customerId]\n  | order(createdAt desc) {\n    _id,\n    orderId,\n    status,\n    totalAmount,\n    createdAt\n  }\n": ORDERS_BY_CUSTOMER_ID_QUERYResult;
    "\n*[\n  _type == \"product\"\n  && (!defined($search) || title match $search + \"*\")\n  && (!defined($category) || $category in categories[]->slug.current)\n  && (!defined($minPrice) || price >= $minPrice)\n  && (!defined($maxPrice) || price <= $maxPrice)\n  && (!defined($inStock) || inStock == $inStock)\n] | order(\n  select($sort == \"price_asc\" => price) asc,\n  select($sort == \"price_desc\" => price) desc,\n  select($sort == \"newest\" => _createdAt) desc,\n  title asc\n)[$start...$end] {\n  \n  _id,\n  title,\n  description,\n  price,\n  discountPrice,\n  featured,\n  inStock,\n  quantity,\n  _createdAt,\n  createdAt,\n\n  slug {\n    current\n  },\n\n  image {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  gallery[] {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    slug {\n      current\n    }\n  },\n\n  colors[]{\n    name,\n    hex\n  },\n\n  sizes,\n\n  variants[]{\n    sku,\n    color,\n    size,\n    price,\n    inStock,\n    quantity\n  }\n\n}\n": FILTER_PRODUCTS_MASTER_QUERYResult;
    "\n*[_type == \"product\" && slug.current == $slug][0]{\n  _id,\n  title,\n  description,\n  price,\n  discountPrice,\n  inStock,\n  quantity,\n  createdAt,\n\n  \"images\": gallery[].asset->url,\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n\n  colors[]{\n    name,\n    hex\n  },\n\n  sizes,\n\n  variants[]{\n    sku,\n    color,\n    size,\n    price,\n    inStock,\n    quantity\n  }\n}\n": PRODUCT_BY_SLUG_QUERYResult;
    "\n  *[_type == \"product\" && featured == true] | order(_createdAt desc) { \n  _id,\n  title,\n  description,\n  price,\n  discountPrice,\n  featured,\n  inStock,\n  quantity,\n  _createdAt,\n  createdAt,\n\n  slug {\n    current\n  },\n\n  image {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  gallery[] {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    slug {\n      current\n    }\n  },\n\n  colors[]{\n    name,\n    hex\n  },\n\n  sizes,\n\n  variants[]{\n    sku,\n    color,\n    size,\n    price,\n    inStock,\n    quantity\n  }\n }\n": FEATURED_PRODUCTS_QUERYResult;
    "\ncount(\n  *[\n    _type == \"product\"\n    && (!defined($search) || title match $search + \"*\")\n    && (!defined($category) || $category in categories[]->slug.current)\n    && (!defined($minPrice) || price >= $minPrice)\n    && (!defined($maxPrice) || price <= $maxPrice)\n    && (!defined($inStock) || inStock == $inStock)\n  ]\n)\n": FILTERED_PRODUCT_COUNT_QUERYResult;
    "\n*[\n  _type == \"product\"\n  // Only filter by name if $name is actually provided\n  && (!defined($name) || title match $name + \"*\")\n] | order(title asc) {\n  \n  _id,\n  title,\n  description,\n  price,\n  discountPrice,\n  featured,\n  inStock,\n  quantity,\n  _createdAt,\n  createdAt,\n\n  slug {\n    current\n  },\n\n  image {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  gallery[] {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    slug {\n      current\n    }\n  },\n\n  colors[]{\n    name,\n    hex\n  },\n\n  sizes,\n\n  variants[]{\n    sku,\n    color,\n    size,\n    price,\n    inStock,\n    quantity\n  }\n\n}\n": FILTER_PRODUCTS_BY_NAME_QUERYResult;
    "\n  *[_type == \"product\"] | order(price asc) {\n    \n  _id,\n  title,\n  description,\n  price,\n  discountPrice,\n  featured,\n  inStock,\n  quantity,\n  _createdAt,\n  createdAt,\n\n  slug {\n    current\n  },\n\n  image {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  gallery[] {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    slug {\n      current\n    }\n  },\n\n  colors[]{\n    name,\n    hex\n  },\n\n  sizes,\n\n  variants[]{\n    sku,\n    color,\n    size,\n    price,\n    inStock,\n    quantity\n  }\n\n  }\n": FILTER_PRODUCTS_BY_PRICE_ASC_QUERYResult;
    "\n  *[_type == \"product\"] | order(price desc) [$start...$end] {\n    \n  _id,\n  title,\n  description,\n  price,\n  discountPrice,\n  featured,\n  inStock,\n  quantity,\n  _createdAt,\n  createdAt,\n\n  slug {\n    current\n  },\n\n  image {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  gallery[] {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    slug {\n      current\n    }\n  },\n\n  colors[]{\n    name,\n    hex\n  },\n\n  sizes,\n\n  variants[]{\n    sku,\n    color,\n    size,\n    price,\n    inStock,\n    quantity\n  }\n\n  }\n": FILTER_PRODUCTS_BY_PRICE_DESC_QUERYResult;
    "\n*[_type == \"product\" && (title match $search + \"*\" || description match $search + \"*\")] \n| order(\n  select(\n    title match $search + \"*\" => 2,\n    description match $search + \"*\" => 1,\n    0\n  ) desc,\n  title asc\n) [$start...$end] {\n  \n  _id,\n  title,\n  description,\n  price,\n  discountPrice,\n  featured,\n  inStock,\n  quantity,\n  _createdAt,\n  createdAt,\n\n  slug {\n    current\n  },\n\n  image {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  gallery[] {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    slug {\n      current\n    }\n  },\n\n  colors[]{\n    name,\n    hex\n  },\n\n  sizes,\n\n  variants[]{\n    sku,\n    color,\n    size,\n    price,\n    inStock,\n    quantity\n  }\n\n}\n": FILTER_PRODUCTS_BY_RELEVANCE_QUERYResult;
    "\n  *[_type == \"product\" && _id in $ids] {\n    _id,\n    quantity\n  }\n": PRODUCTS_BY_IDS_QUERYResult;
    "\n  count(*[_type == \"product\"])\n": TOTAL_PRODUCTS_QUERYResult;
    "\n  count(*[_type == \"product\" && inStock == true])\n": IN_STOCK_PRODUCTS_COUNT_QUERYResult;
    "\n  count(*[_type == \"product\" && inStock == false])\n": OUT_OF_STOCK_PRODUCTS_COUNT_QUERYResult;
    "\n  count(*[_type == \"product\" && quantity < $threshold])\n": LOW_STOCK_PRODUCTS_COUNT_QUERYResult;
    "\n  count(*[_type == \"product\" && featured == true])\n": FEATURED_PRODUCTS_COUNT_QUERYResult;
    "\n  count(*[_type == \"product\" && defined(discountPrice)])\n": DISCOUNTED_PRODUCTS_COUNT_QUERYResult;
    "\n  count(*[_type == \"category\"])\n": TOTAL_CATEGORIES_QUERYResult;
    "\n  count(*[_type == \"customer\"])\n": TOTAL_CUSTOMERS_QUERYResult;
    "\n  count(*[_type == \"customer\" && defined(stripeCustomerId)])\n": STRIPE_CUSTOMERS_COUNT_QUERYResult;
    "\n  count(*[_type == \"order\" && status == \"pending\"])\n": PENDING_ORDERS_COUNT_QUERYResult;
    "\n  count(*[_type == \"order\" && status == \"processing\"])\n": PROCESSING_ORDERS_COUNT_QUERYResult;
    "\n  count(*[_type == \"order\" && status == \"shipped\"])\n": SHIPPED_ORDERS_COUNT_QUERYResult;
    "\n  count(*[_type == \"order\" && status == \"delivered\"])\n": DELIVERED_ORDERS_COUNT_QUERYResult;
    "\n  count(*[_type == \"order\" && status == \"cancelled\"])\n": CANCELLED_ORDERS_COUNT_QUERYResult;
    "\n  {\n    \"totalRevenue\": math::sum(\n      *[_type == \"order\" && status == \"completed\"].total\n    )\n  }\n": STATS_TOTAL_REVENUE_QUERYResult;
    "\n{\n  \"todayRevenue\": math::sum(\n    *[\n      _type == \"order\"\n      && status == \"completed\"\n      && createdAt >= dateTime(now()) - 60*60*24\n    ].total\n  )\n}\n": TODAY_REVENUE_QUERYResult;
    "\n{\n  \"monthRevenue\": math::sum(\n    *[\n      _type == \"order\"\n      && status == \"completed\"\n      && createdAt >= dateTime(now()) - 60*60*24*30\n    ].total\n  )\n}\n": MONTH_REVENUE_QUERYResult;
    "\n  math::avg(*[_type == \"order\" && status == \"paid\"].totalAmount)\n": AVERAGE_ORDER_VALUE_QUERYResult;
    "\n  math::max(*[_type == \"order\" && status == \"paid\"].totalAmount)\n": MAX_ORDER_VALUE_QUERYResult;
    "\n  count(\n    *[\n      _type == \"order\" &&\n      (status == \"pending\" || status == \"processing\")\n    ]\n  )\n": ATTENTION_ORDERS_COUNT_QUERYResult | UNFULFILLED_ORDERS_COUNT_QUERYResult;
    "\n*[\n  _type == \"order\"\n  && createdAt >= dateTime(now()) - 60*60*24*7\n]\n": ORDERS_LAST_7_DAYS_QUERYResult;
    "\ncount(\n  *[\n    _type == \"order\"\n    && createdAt >= dateTime(now()) - 60*60*24*7\n  ]\n)\n": ORDERS_LAST_7_DAYS_COUNT_QUERYResult;
    "\n{\n  \"pending\": count(*[_type == \"order\" && status == \"pending\"]),\n  \"processing\": count(*[_type == \"order\" && status == \"processing\"]),\n  \"shipped\": count(*[_type == \"order\" && status == \"shipped\"]),\n  \"delivered\": count(*[_type == \"order\" && status == \"delivered\"]),\n  \"cancelled\": count(*[_type == \"order\" && status == \"cancelled\"])\n}\n": ORDER_STATUS_DISTRIBUTION_QUERYResult;
    "\n  *[_type == \"product\"] {\n    \n  _id,\n  title,\n  description,\n  price,\n  discountPrice,\n  featured,\n  inStock,\n  quantity,\n  _createdAt,\n  createdAt,\n\n  slug {\n    current\n  },\n\n  image {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  gallery[] {\n    asset->{\n      _id,\n      url\n    }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    slug {\n      current\n    }\n  },\n\n  colors[]{\n    name,\n    hex\n  },\n\n  sizes,\n\n  variants[]{\n    sku,\n    color,\n    size,\n    price,\n    inStock,\n    quantity\n  }\n,\n    \"salesCount\": count(*[_type == \"order\" && references(^._id)])\n  } | order(salesCount desc)[0...5]\n": TOP_SELLING_PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\"] {\n    _id,\n    title,\n    \"totalRevenue\": math::sum(*[_type == \"order\" && references(^._id)].items[product._ref == ^.^._id].price)\n  } | order(totalRevenue desc)[0...5]\n": TOP_SELLING_PRODUCTS_AGGREGATED_QUERYResult;
    "\n  *[\n    _type == \"order\" &&\n    (\n      status == \"pending\" ||\n      status == \"processing\"\n    )\n  ] | order(createdAt asc) {\n    _id,\n    orderId,\n    totalAmount,\n    status,\n    createdAt,\n    customer->{\n      _id,\n      name,\n      email\n    },\n    items[]{\n      title,\n      quantity\n    }\n  }\n": UNFULFILLED_ORDERS_QUERYResult;
    "\n{\n  \"salesLast7Days\": math::sum(\n    *[\n      _type == \"order\"\n      && status == \"completed\"\n      && createdAt >= dateTime(now()) - 60*60*24*7\n    ].total\n  )\n}\n": SALES_LAST_7_DAYS_QUERYResult;
  }
}
